### ISSUE TITLE
Delete Category Button is not working

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#155]
When trying to delete a category, an error accures

**Comment by LuposX** [comment]
![Screenshot from 2023-02-22 13-05-43](https://user-images.githubusercontent.com/36456825/220615195-79e71657-c99a-43da-9094-db2d1066dc70.png)

The problem lies in this code place, in the category_frame class, it does nothing when false gets returned.
When the selected category is the building category than it will not be deleted and thus rteurns false, but it doesnt do anything with that false.

**Solution:** Create a popup when false is returned, also close the popup immeditely which asks for confirmation immedtiedly.
![Screenshot from 2023-02-22 13-07-17](https://user-images.githubusercontent.com/36456825/220615533-1bdba619-e065-4756-8171-982a5416af61.png)

**Comment by calliminator** [comment]
fixxed
